build-adoc:
  image: asciidoctor/docker-asciidoctor
  script:
    - make ci-adoc
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - "docs"

build-pandoc:
  image:
    name: pandoc/core
    entrypoint: [ "/bin/sh", "-c" ]
  needs:
    - build-adoc
  script: ./generate-docx.sh
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - "docs"

pages:
  image: alpine
  needs:
    - build-adoc
    - build-pandoc
  script:
    - mkdir -p public
    - cp -R docs/* public
  artifacts:
    paths:
      - "public"