[#main_title]
= template-asciidoctor-dockerized

:hide-uri-scheme:
:lang: FR
:imagesdir: {docdir}/readme/assets

:back_to_top_target: top-target
:back_to_top_label: ⬆ Retour au début
:back_to_top: <<main_title,{back_to_top_label}>>

Génération de slides, pdf, ebook, docx à l'aide de https://docs.asciidoctor.org/asciidoctor/latest/[Asciidoctor,window=_blank], https://docs.asciidoctor.org/reveal.js-converter/latest/[RevealJs,window=_blank] et https://docs.docker.com/compose/[Docker Compose,window=_blank].

Ce dépôt a été généré à partir du template : https://github.com/baldir-fr/template-asciidoctor-dockerized[window=_blank]

== Documents générés

* link:docs/index.html[Slides générées au format HTML,window=_blank]
* link:docs/output.pdf[Pdf,window=_blank]
* link:docs/output.epub[Ebook,window=_blank]
* link:docs/output.docbook.xml[Docbook,window=_blank]
* link:docs/output.docx[Docx,window=_blank]

{back_to_top}

== Écrire du contenu

Modifier les fichiers présents dans link:01-slides/[`01-slides`].

Voir la section <<_ressources-asciidoctor-complementaires,Ressources Asciidoctor complémentaires>> pour démarrer avec Asciidoctor et RevealJs.

{back_to_top}

[#_ressources-asciidoctor-complementaires]
== Ressources Asciidoctor complémentaires

include::readme/ressources-asciidoctor-complementaires.adoc[➡️ Ressources Asciidoctor complémentaires]

{back_to_top}

== Génération du contenu

=== Pré-requis pour construire les exemples

* Docker Engine 19.03.0+
* Docker compose

Optionnel

* GNU Make

=== Génération des slides

[source,shell]
----
docker compose run build-slides
# Ou avec GNU Make
make 01-slides
----

=== Génération du Pdf

[source,shell]
----
docker compose run --rm build-slides; rm -rf docs/assets;cp -r 01-slides/assets docs/
# Ou avec GNU Make
make 01-pdf
----

=== Génération de l'E-book

[source,shell]
----
docker compose run build-epub
# Ou avec GNU Make
make 01-epub
----

[#_generation_du_docbook]
=== Génération du docbook

[source,shell]
----
docker compose run build-docbook
# Ou avec GNU Make
make 01-docbook
----

=== Génération docx

Prérequis : avoir pandoc installé (je n'ai pas encore réussi à le faire fonctionner avec docker)

Après avoir <<_generation_du_docbook,généré le docbook>>

[source,shell]
----
pandoc --from docbook \
  --to docx \
  --toc \
  --highlight-style tango \
  -o docs/output.docx \
  --resource-path=docs \
  docs/output.docbook.xml
----

{back_to_top}

== Déploiement

include::readme/deploiement.adoc[➡️ Méthodes de déploiement]

{back_to_top}
