name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:

  build-adoc:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor
    steps:
      - uses: actions/checkout@v3
      - name: Use asciidoctor to build content
        run: |
          make ci-adoc
          ls -al docs

  build-pandoc:
    needs: build-adoc
    runs-on: ubuntu-latest
    container: pandoc/core
    steps:
      - uses: actions/checkout@v3
      - name: Use pandoc to convert content
        run: |
          pandoc --from docbook --to docx --toc --highlight-style tango -o docs/output.docx docs/output.docbook.xml --resource-path=docs
          ls -al docs
