name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: asciidoctor/docker-asciidoctor

    steps:
    - uses: actions/checkout@v3
    
    # - name: configure
    #  run: ./configure
      
    - name: Generate output from Asciidoctor
      run: make ci-adoc
